package jp.hanatoya.ipcam.repo;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig camDaoConfig;
    private final DaoConfig switchDaoConfig;

    private final CamDao camDao;
    private final SwitchDao switchDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        camDaoConfig = daoConfigMap.get(CamDao.class).clone();
        camDaoConfig.initIdentityScope(type);

        switchDaoConfig = daoConfigMap.get(SwitchDao.class).clone();
        switchDaoConfig.initIdentityScope(type);

        camDao = new CamDao(camDaoConfig, this);
        switchDao = new SwitchDao(switchDaoConfig, this);

        registerDao(Cam.class, camDao);
        registerDao(Switch.class, switchDao);
    }
    
    public void clear() {
        camDaoConfig.clearIdentityScope();
        switchDaoConfig.clearIdentityScope();
    }

    public CamDao getCamDao() {
        return camDao;
    }

    public SwitchDao getSwitchDao() {
        return switchDao;
    }

}
