package jp.hanatoya.ipcam.repo;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "SWITCH".
*/
public class SwitchDao extends AbstractDao<Switch, Long> {

    public static final String TABLENAME = "SWITCH";

    /**
     * Properties of entity Switch.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Cgi = new Property(2, String.class, "cgi", false, "CGI");
        public final static Property Port = new Property(3, int.class, "port", false, "PORT");
        public final static Property CamId = new Property(4, long.class, "camId", false, "CAM_ID");
    }


    public SwitchDao(DaoConfig config) {
        super(config);
    }

    public SwitchDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SWITCH\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"CGI\" TEXT NOT NULL ," + // 2: cgi
                "\"PORT\" INTEGER NOT NULL ," + // 3: port
                "\"CAM_ID\" INTEGER NOT NULL );"); // 4: camId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SWITCH\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Switch entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getCgi());
        stmt.bindLong(4, entity.getPort());
        stmt.bindLong(5, entity.getCamId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Switch entity) {
        stmt.clearBindings();

        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindString(3, entity.getCgi());
        stmt.bindLong(4, entity.getPort());
        stmt.bindLong(5, entity.getCamId());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }

    @Override
    public Switch readEntity(Cursor cursor, int offset) {
        Switch entity = new Switch( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getString(offset + 2), // cgi
            cursor.getInt(offset + 3), // port
            cursor.getLong(offset + 4) // camId
        );
        return entity;
    }

    @Override
    public void readEntity(Cursor cursor, Switch entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setCgi(cursor.getString(offset + 2));
        entity.setPort(cursor.getInt(offset + 3));
        entity.setCamId(cursor.getLong(offset + 4));
     }

    @Override
    protected final Long updateKeyAfterInsert(Switch entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }

    @Override
    public Long getKey(Switch entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Switch entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
