package mobileyed.hanatoya.jp.models;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CAM".
 */
public class Cam {

    private Long id = -1l;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String name;
    /** Not-null value. */
    private String host;
    /** Not-null value. */
    private String protocol = "http://";
    private int port;
    private String username;
    private String password;
    private Integer status;
    private byte[] snap;


    public Cam() {
    }

    public Cam(Long id) {
        this.id = id;
    }

    public Cam(Long id, String type, String name, String host, String protocol, int port, String username, String password, Integer status, byte[] snap) {
        this.id = id;
        this.type = type;
        this.name = name;
        this.host = host;
        this.protocol = protocol;
        this.port = port;
        this.username = username;
        this.password = password;
        this.status = status;
        this.snap = snap;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(String name) {
        this.name = name;
    }

    /** Not-null value. */
    public String getHost() {
        return host;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHost(String host) {
        this.host = host;
    }

    /** Not-null value. */
    public String getProtocol() {
        return protocol;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setProtocol(String protocol) {
        this.protocol = protocol;
    }

    public int getPort() {
        return port;
    }

    public void setPort(int port) {
        this.port = port;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public byte[] getSnap() {
        return snap;
    }

    public void setSnap(byte[] snap) {
        this.snap = snap;
    }

    public String getStreamUrl(){
        StringBuilder sb = new StringBuilder(this.getProtocol());
        sb.append(this.getHost());
        sb.append(":");
        sb.append(this.port);
        if(this.type.equals("Panasonic VL-CM210")){
            sb.append("/nphMotionJpeg?Resolution=640x480&Quality=High").toString();
        }else if (this.type.equals("Planex CS-WMV043G-NV")){
            sb.append("/mjpg/video.mjpg");
        }
        return sb.toString();
    }
}
